"""set_null_routine_session_conversation_fk

Revision ID: 1a63104f3a63
Revises: a2dbaf2c0359
Create Date: 2026-06-19 16:17:15.136697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a63104f3a63'
down_revision: Union[str, None] = 'a2dbaf2c0359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('routine_sessions_conversation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'orbit_conversations', ['conversation_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('routine_sessions_conversation_id_fkey', 'orbit_conversations', ['conversation_id'], ['id'])

    # ### end Alembic commands ###
