"""Add state machine columns to OrbitConversation

Revision ID: 373f5ecb5d33
Revises: 6a24ae1c9e8e
Create Date: 2026-06-10 15:56:28.825981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373f5ecb5d33'
down_revision: Union[str, None] = '6a24ae1c9e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orbit_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('original_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('clarification_answers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orbit_conversations', schema=None) as batch_op:
        batch_op.drop_column('clarification_answers')
        batch_op.drop_column('original_prompt')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
