"""Add UserAIUsage and subscription_plan

Revision ID: 58208bcccf3f
Revises: 
Create Date: 2026-06-04 23:00:36.813366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58208bcccf3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.String(length=50), server_default='free', nullable=False))

    op.execute("DROP TABLE IF EXISTS user_ai_usage CASCADE")
    op.create_table('user_ai_usage',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('routine_generations', sa.Integer(), nullable=False),
        sa.Column('audio_transcriptions', sa.Integer(), nullable=False),
        sa.Column('clarification_requests', sa.Integer(), nullable=False),
        sa.Column('analysis_requests', sa.Integer(), nullable=False),
        sa.Column('last_request_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'date', name='uq_user_daily_usage')
    )
    op.create_index(op.f('ix_user_ai_usage_date'), 'user_ai_usage', ['date'], unique=False)
    op.create_index(op.f('ix_user_ai_usage_id'), 'user_ai_usage', ['id'], unique=False)
    op.create_index(op.f('ix_user_ai_usage_user_id'), 'user_ai_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ai_usage_user_id'), table_name='user_ai_usage')
    op.drop_index(op.f('ix_user_ai_usage_id'), table_name='user_ai_usage')
    op.drop_index(op.f('ix_user_ai_usage_date'), table_name='user_ai_usage')
    op.drop_table('user_ai_usage')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_plan')

    # ### end Alembic commands ###
