"""add orbit conversations messages task memory behavioral memory

Revision ID: 6a24ae1c9e8e
Revises: 58208bcccf3f
Create Date: 2026-06-10 14:53:21.900262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a24ae1c9e8e'
down_revision: Union[str, None] = '58208bcccf3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
