"""add routine sessions

Revision ID: a2dbaf2c0359
Revises: 373f5ecb5d33
Create Date: 2026-06-19 15:59:01.683754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2dbaf2c0359'
down_revision: Union[str, None] = '373f5ecb5d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_routines_session_id'), ['session_id'], unique=False)
        batch_op.create_foreign_key(None, 'routine_sessions', ['session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_routines_session_id'))
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
