"""add v2_1 priority fields

Revision ID: af8d08b7e03d
Revises: b675472a7595
Create Date: 2026-06-19 17:20:42.026086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8d08b7e03d'
down_revision: Union[str, None] = 'b675472a7595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('importance_score', sa.Integer(), server_default='5', nullable=False))
    op.add_column('routines', sa.Column('deadline_score', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_column('deadline_score')
        batch_op.drop_column('importance_score')

    # ### end Alembic commands ###
