"""add_v2_cognitive_fields_to_routines

Revision ID: b675472a7595
Revises: f376146eb284
Create Date: 2026-06-19 16:58:12.018671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b675472a7595'
down_revision: Union[str, None] = 'f376146eb284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy_score', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('complexity_score', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('urgency_score', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fixed_time', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('actual_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scheduling_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_column('scheduling_reason')
        batch_op.drop_column('actual_duration')
        batch_op.drop_column('category')
        batch_op.drop_column('fixed_time')
        batch_op.drop_column('deadline')
        batch_op.drop_column('location')
        batch_op.drop_column('urgency_score')
        batch_op.drop_column('complexity_score')
        batch_op.drop_column('energy_score')

    # ### end Alembic commands ###
